apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apprest
  template:
    metadata:
      labels:
        app: apprest
    spec:
      containers:
      - name: apprest
        image: us.gcr.io/synthetic-song-226517/demo/apprest:latest
        ports:
        - containerPort: 8081
          name: apprest  
